# Combined galaxy_ng base + dev image
# This merges galaxy_ng/Dockerfile and dev/compose/Dockerfile.dev
# into a single build so we don't need BuildKit's additional_contexts
#
# Build context should be the galaxy_ng directory

FROM localhost/galaxy_ng/galaxy_ng:base

ARG GNUPGHOME="/etc/pulp/gnupg/"
ENV GNUPGHOME="${GNUPGHOME}"

USER root
RUN LANG=C dnf -y --disableplugin=subscription-manager install nc

USER galaxy
RUN ${VIRTUAL_ENV}/bin/python3 -m pip install debugpy hupper ipython ipdb rpdb django-extensions pulp-cli

RUN /app/dev/compose/signing/setup_gpg_workarounds.sh

COPY --chown=galaxy:galaxy dev/compose/database/database_fields.symmetric.key /etc/pulp/certs/database_fields.symmetric.key
COPY --chown=galaxy:galaxy dev/compose/signing/keys /etc/pulp/certs/
COPY --chown=galaxy:galaxy dev/compose/signing/scripts /var/lib/pulp/scripts/

RUN set -ex; \
    chmod -R 0775 /etc/pulp/certs /var/lib/pulp/scripts && \
    /app/dev/compose/signing/setup_gpg_keys.sh
